FROM fopina/alpine-arm:3.6

RUN [ "cross-build-start" ]
RUN apk add --no-cache openssh-server tor s6
RUN echo PermitRootLogin yes >> /etc/ssh/sshd_config
RUN [ "cross-build-end" ]

COPY entry.sh /entry.sh
COPY torrc.tpl /etc/tor/torrc.tpl

ENV TOR_PORT 9999

ENTRYPOINT ["/entry.sh"]

CMD ["/usr/sbin/sshd", "-D", "-f", "/etc/ssh/sshd_config"]